# RUNBOOK — build.
#
#   make            build build/runbook
#   make check      the gates: --health, then determinism
#   make health     the health gate alone
#   make windows    cross-build the Windows binary (needs mingw-w64)
#   make clean
#
# ONE C COMPILER, ONE LINK, NO THIRD-PARTY LIBRARIES. A single self-contained
# binary per platform is a locked target (handoff decision 3), and every
# dependency added here is a dependency the player's machine has to satisfy.
#
# The floating point flags are load-bearing, not decoration: contraction and
# fast-math let the compiler reassociate arithmetic, which breaks the
# byte-identical replay guarantee that decision 16 rests on. Nothing in the
# model uses a double yet — the flags are here now so that the day one lands,
# it lands already pinned, instead of being retrofitted after the Windows
# build starts disagreeing with the Linux one.

CC      ?= cc
CSTD     = -std=c11
# POSIX for clock_gettime, which the harness uses to report wall time. The
# world model never sees it: nothing in the simulation may depend on a clock.
CSTD    += -D_POSIX_C_SOURCE=200809L
WARN     = -Wall -Wextra -Wno-unused-parameter
FPFLAGS  = -ffp-contract=off -fno-fast-math
OPT     ?= -O2
# -MMD -MP: without header dependencies, editing world.h rebuilds only world.o
# and every other object keeps the old struct layout. That fails as a segfault,
# not as a compile error. Do not remove.
CFLAGS  += $(CSTD) $(WARN) $(FPFLAGS) $(OPT) -Icore -MMD -MP
LDFLAGS +=

# THE CORE IS A LIBRARY. main.c is the only file below that knows a command
# line exists; everything else is linked, unchanged, into the GDExtension when
# the client arrives at M3. If a source file here ever needs to know whether it
# is running under Godot, the model/view rule has already been broken.
CORE_SRC = core/util.c core/yaml.c core/spec.c core/appl.c core/ticket.c core/world.c \
           core/proto.c core/serve.c core/health.c core/mancheck.c core/play.c
CORE_OBJ = $(CORE_SRC:core/%.c=build/%.o)
MAIN_OBJ = build/main.o

BIN = build/runbook

# The default goal is pinned: a rule defined above `all:` would otherwise
# become the default and silently build the wrong thing.
.DEFAULT_GOAL := all

.PHONY: all check health mancheck play naive vacation determinism clean windows specs

all: $(BIN)

$(BIN): $(CORE_OBJ) $(MAIN_OBJ) | build
	$(CC) -o $@ $(CORE_OBJ) $(MAIN_OBJ) $(LDFLAGS)

build:
	@mkdir -p build

build/%.o: core/%.c | build
	$(CC) $(CFLAGS) -c -o $@ $<

# The embedded specs. Regenerated by hand (tools/mkspecs.sh) and committed,
# for the reason given in that script; this rule is here so that forgetting to
# run it fails the build rather than shipping a stale appliance library.
core/specbin.h: $(wildcard specs/*.yaml) tools/mkspecs.sh
	@./tools/mkspecs.sh

specs: core/specbin.h

build/spec.o: core/specbin.h

# ---------------------------------------------------------------- the gates
# M0's whole deliverable. Nothing else starts until these are green
# (handoff §15).
check: health mancheck play naive vacation determinism

health: $(BIN)
	@./$(BIN) --health

mancheck: $(BIN)
	@./$(BIN) --mancheck

# THE BALANCE HARNESS (§13). --play says a competent script can keep up;
# --naive-gate says an incompetent one cannot. Neither number is a vibe check
# and neither is tuned by argument: every constant in the growth model, the
# exception ramp and the failure rates was set by running these.
play: $(BIN)
	@./$(BIN) --play --days 60

naive: $(BIN)
	@./$(BIN) --naive-gate

# THE WIN CONDITION, AS A GATE (§12). Seven simulated days at four thousand
# users with nobody watching. If the reference automation cannot go on holiday,
# neither can a player's, and the endgame does not exist.
vacation: $(BIN)
	@./$(BIN) --vacation 7

determinism: $(BIN)
	@./tools/check_determinism.sh

# ------------------------------------------------------------------ windows
# Windows is a target, not a port (handoff §0). It is cross-built here so the
# determinism gate can compare the two binaries' output; if this rule rots,
# the cross-platform half of decision 16 rots with it and nothing says so.
WINCC    ?= x86_64-w64-mingw32-gcc
WINFLAGS  = $(CSTD) $(WARN) $(FPFLAGS) $(OPT) -Icore -static
WIN_BIN   = build/win/runbook.exe

windows: $(WIN_BIN)

$(WIN_BIN): $(CORE_SRC) core/main.c
	@mkdir -p build/win
	$(WINCC) $(WINFLAGS) $(CORE_SRC) core/main.c -o $@ -lws2_32

clean:
	rm -rf build

-include $(CORE_OBJ:.o=.d) $(MAIN_OBJ:.o=.d)
