# RUNBOOK — build.
#
#   make            build build/runbook
#   make check      the gates: --health, then determinism
#   make health     the health gate alone
#   make windows    cross-build the Windows binary (needs mingw-w64)
#   make clean
#
# ONE C COMPILER, ONE LINK, NO THIRD-PARTY LIBRARIES. A single self-contained
# binary per platform is a locked target (handoff decision 3), and every
# dependency added here is a dependency the player's machine has to satisfy.
#
# The floating point flags are load-bearing, not decoration: contraction and
# fast-math let the compiler reassociate arithmetic, which breaks the
# byte-identical replay guarantee that decision 16 rests on. Nothing in the
# model uses a double yet — the flags are here now so that the day one lands,
# it lands already pinned, instead of being retrofitted after the Windows
# build starts disagreeing with the Linux one.

CC      ?= cc
CSTD     = -std=c11
# POSIX for clock_gettime, which the harness uses to report wall time. The
# world model never sees it: nothing in the simulation may depend on a clock.
CSTD    += -D_POSIX_C_SOURCE=200809L
WARN     = -Wall -Wextra -Wno-unused-parameter
FPFLAGS  = -ffp-contract=off -fno-fast-math
OPT     ?= -O2
# -MMD -MP: without header dependencies, editing world.h rebuilds only world.o
# and every other object keeps the old struct layout. That fails as a segfault,
# not as a compile error. Do not remove.
CFLAGS  += $(CSTD) $(WARN) $(FPFLAGS) $(OPT) -Icore -Imachine -MMD -MP
LDFLAGS +=

# THE CORE IS A LIBRARY. main.c is the only file below that knows a command
# line exists; everything else is linked, unchanged, into the GDExtension when
# the client arrives at M3. If a source file here ever needs to know whether it
# is running under Godot, the model/view rule has already been broken.
CORE_SRC = core/util.c core/yaml.c core/spec.c core/appl.c core/ticket.c core/recorder.c core/world.c \
           core/proto.c core/serve.c core/box.c core/health.c core/mancheck.c core/boxcheck.c core/play.c

# THE MACHINE, LIFTED FROM NOMINAL AND BUILT UNCHANGED.
#
# An RV64IM emulator, a kernel, a package database, a boot chain and a virtual
# filesystem -- about eleven thousand lines that have been debugged against
# real play. They compile against machine/nom.h, a shim that says nom_alloc is
# rb_alloc and little else; see the note at the top of it for why not one line
# of them was edited.
#
# Two exceptions, both documented where they are: one syscall (SYS_rbapi, the
# bridge a script uses to reach the game) and one line in image.c that puts
# /bin/rb on the disk.
#
# They are a SEPARATE variable rather than folded into CORE_SRC so that this
# distinction stays visible in the build: everything in core/ is ours and
# everything in machine/ is borrowed.
MACHINE_SRC = machine/cpu.c machine/kernel.c machine/image.c machine/boot.c \
              machine/vfs.c machine/ns.c machine/nonet.c
CORE_OBJ = $(CORE_SRC:core/%.c=build/%.o) $(MACHINE_SRC:machine/%.c=build/m_%.o)
MAIN_OBJ = build/main.o

BIN = build/runbook

# The default goal is pinned: a rule defined above `all:` would otherwise
# become the default and silently build the wrong thing.
.DEFAULT_GOAL := all

.PHONY: all check health mancheck machine play naive vacation client determinism clean windows specs gdext run shot

all: $(BIN)

$(BIN): $(CORE_OBJ) $(MAIN_OBJ) | build
	$(CC) -o $@ $(CORE_OBJ) $(MAIN_OBJ) $(LDFLAGS)

build:
	@mkdir -p build

build/%.o: core/%.c | build
	$(CC) $(CFLAGS) -c -o $@ $<

# The borrowed half. -Wno-format-truncation because these files are lifted
# unchanged and gcc has opinions about two of their snprintf calls that the
# code has already thought about; fixing them here would mean maintaining a
# fork of somebody else's debugged kernel.
build/m_%.o: machine/%.c | build
	$(CC) $(CFLAGS) -Imachine -Wno-format-truncation -c -o $@ $<

# The embedded specs. Regenerated by hand (tools/mkspecs.sh) and committed,
# for the reason given in that script; this rule is here so that forgetting to
# run it fails the build rather than shipping a stale appliance library.
core/specbin.h: $(wildcard specs/*.yaml) tools/mkspecs.sh
	@./tools/mkspecs.sh

specs: core/specbin.h

build/spec.o: core/specbin.h

# ---------------------------------------------------------------- the gates
# M0's whole deliverable. Nothing else starts until these are green
# (handoff §15).
check: health mancheck machine play naive vacation client determinism

health: $(BIN)
	@./$(BIN) --health

mancheck: $(BIN)
	@./$(BIN) --mancheck

# THE MACHINE (M4, decision 13). The moat: a real RV64IM computer under the
# desktop, with a real shell, real files and the game one program away.
machine: $(BIN)
	@./$(BIN) --machine

# THE BALANCE HARNESS (§13). --play says a competent script can keep up;
# --naive-gate says an incompetent one cannot. Neither number is a vibe check
# and neither is tuned by argument: every constant in the growth model, the
# exception ramp and the failure rates was set by running these.
play: $(BIN)
	@./$(BIN) --play --days 60

naive: $(BIN)
	@./$(BIN) --naive-gate

# THE WIN CONDITION, AS A GATE (§12). Seven simulated days at four thousand
# users with nobody watching. If the reference automation cannot go on holiday,
# neither can a player's, and the endgame does not exist.
vacation: $(BIN)
	@./$(BIN) --vacation 7

determinism: $(BIN)
	@./tools/check_determinism.sh

# PLAY IT. One command, and it finds a Godot the same way the gate does.
run: gdext
	@GODOT=$${GODOT:-$$(ls -1 $(HOME)/NOMINAL/Godot_v4.*-stable_linux.x86_64 \
	   ./Godot_v4.*-stable_linux.x86_64 2>/dev/null | head -1)}; \
	 if [ ! -x "$$GODOT" ]; then \
	   echo "no Godot found. Set GODOT=/path/to/godot, or drop the binary in this directory."; \
	   exit 1; \
	 fi; \
	 echo "runbook: $$GODOT"; \
	 "$$GODOT" --path game

# A picture of the desktop, without borrowing anybody's screen. Every
# screenshot in the README comes from here, so what is shown is what the code
# actually draws.
shot: gdext
	@GODOT=$${GODOT:-$$(ls -1 $(HOME)/NOMINAL/Godot_v4.*-stable_linux.x86_64 \
	   ./Godot_v4.*-stable_linux.x86_64 2>/dev/null | head -1)}; \
	 RUNBOOK_SHOT=$(PWD)/docs/desk.png "$$GODOT" --path game -s tests/shot.gd

# THE CLIENT (M3). Skips cleanly when there is no Godot on the box; the C
# gates are the ones that must be green everywhere.
client: gdext
	@./tools/client_gate.sh
	@./tools/client_gate.sh games

# ------------------------------------------------------------------- gdext
# The Godot binding. It links the SAME core the socket and every gate use, so
# the desktop and a telnet session are two front ends onto one implementation
# and cannot disagree.
GDEXT_SO = game/bin/librunbook.linux.x86_64.so

gdext: game/bin/librunbook.linux.x86_64.so

game/bin/librunbook.linux.x86_64.so: $(CORE_SRC) $(MACHINE_SRC) gdext/runbook_gdext.c core/specbin.h
	@mkdir -p game/bin
	$(CC) $(CFLAGS) -Igdext -Wno-format-truncation -fPIC -shared $(CORE_SRC) $(MACHINE_SRC) gdext/runbook_gdext.c -o $@

# ------------------------------------------------------------------ windows
# Windows is a target, not a port (handoff §0). It is cross-built here so the
# determinism gate can compare the two binaries' output; if this rule rots,
# the cross-platform half of decision 16 rots with it and nothing says so.
WINCC    ?= x86_64-w64-mingw32-gcc
WINFLAGS  = $(CSTD) $(WARN) $(FPFLAGS) $(OPT) -Icore -static
WIN_BIN   = build/win/runbook.exe

windows: $(WIN_BIN)

$(WIN_BIN): $(CORE_SRC) $(MACHINE_SRC) core/main.c
	@mkdir -p build/win
	$(WINCC) $(WINFLAGS) -Imachine $(CORE_SRC) $(MACHINE_SRC) core/main.c -o $@ -lws2_32

clean:
	rm -rf build

-include $(CORE_OBJ:.o=.d) $(MAIN_OBJ:.o=.d)
