/* spec.c — loading and validating appliance specs.
 *
 * VALIDATION IS THE POINT OF THIS FILE, not loading. Specs are content, and
 * from M8 they are content written by agents. Every rule checked here is a
 * rule that would otherwise surface as an appliance that silently does
 * nothing, three milestones later, in a playtest. Each one names the file,
 * the endpoint and the field, because "spec error" is not a bug report.
 */
#include "spec.h"
#include "ticket.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#ifndef _WIN32
#  include <dirent.h>
#else
#  include <dirent.h>
#endif

#include "specbin.h"    /* generated by tools/mkspecs.sh; see the note there */

const char *op_name(EndpointOp op)
{
    static const char *const n[OP__N] = { "list", "get", "create", "update", "delete" };
    return (op >= 0 && op < OP__N) ? n[op] : "?";
}

const char *arch_name(VendorArch a)
{
    static const char *const n[VEN__N] = { "good", "cheap", "legacy", "flaky" };
    return (a >= 0 && a < VEN__N) ? n[a] : "?";
}

/* ------------------------------------------------------------- utilities */
typedef struct { char *err; size_t cap; const char *file; bool failed; } Ctx;

static bool sfail(Ctx *c, const char *fmt, ...)
{
    if (c->failed) return false;
    c->failed = true;
    char tmp[400];
    va_list ap; va_start(ap, fmt);
    vsnprintf(tmp, sizeof tmp, fmt, ap);
    va_end(ap);
    snprintf(c->err, c->cap, "%s: %s", c->file, tmp);
    return false;
}

static void cpstr(char *dst, size_t cap, const char *src) { snprintf(dst, cap, "%s", src ? src : ""); }

/* Copy a sequence of scalars into a fixed table, refusing to overflow rather
 * than truncating: an endpoint that quietly loses its last field is a bug
 * that presents as a game balance problem. */
static bool seq_into(Ctx *c, const YNode *seq, char (*out)[RB_NAME_MAX], int cap, int *n, const char *what)
{
    size_t k = y_count(seq);
    if ((int)k > cap) return sfail(c, "%s has %zu entries; the limit is %d", what, k, cap);
    *n = 0;
    for (size_t i = 0; i < k; i++) {
        const YNode *it = y_at(seq, i);
        if (!it || it->kind != Y_SCALAR) return sfail(c, "%s entry %zu is not a name", what, i + 1);
        cpstr(out[(*n)++], RB_NAME_MAX, it->scalar);
    }
    return true;
}

static bool in_table(char (*t)[RB_NAME_MAX], int n, const char *s)
{
    for (int i = 0; i < n; i++) if (!strcmp(t[i], s)) return true;
    return false;
}

/* --------------------------------------------------------------- vendors */
static bool load_vendor(Ctx *c, const YNode *root, Vendor *v)
{
    memset(v, 0, sizeof *v);
    cpstr(v->id,    sizeof v->id,    y_str(root, "vendor", ""));
    cpstr(v->name,  sizeof v->name,  y_str(root, "name", v->id));
    cpstr(v->theme, sizeof v->theme, y_str(root, "theme", "plain"));
    cpstr(v->doc,   sizeof v->doc,   y_str(root, "doc", ""));

    const char *a = y_str(root, "archetype", "");
    if      (!strcmp(a, "good"))   v->arch = VEN_GOOD;
    else if (!strcmp(a, "cheap"))  v->arch = VEN_CHEAP;
    else if (!strcmp(a, "legacy")) v->arch = VEN_LEGACY;
    else if (!strcmp(a, "flaky"))  v->arch = VEN_FLAKY;
    else return sfail(c, "archetype must be good, cheap, legacy or flaky (got '%s')", a);

    v->cost         = y_int(root, "cost", 100);
    /* 60/minute is the handoff §10 baseline; the flaky vendor is meant to
     * sit below it, which is what makes backoff a thing you must write. */
    v->rate_limit   = y_int(root, "rate_limit", 60);
    v->transient_bp = y_int(root, "transient_bp", 300);
    if (!v->id[0]) return sfail(c, "a vendor file needs a 'vendor:' id");
    return true;
}

/* ---------------------------------------------------------------- models */
static bool load_endpoint(Ctx *c, const YNode *e, const Model *m, Endpoint *ep)
{
    memset(ep, 0, sizeof *ep);
    cpstr(ep->id, sizeof ep->id, y_str(e, "id", ""));
    if (!ep->id[0]) return sfail(c, "an endpoint has no id");

    const char *op = y_str(e, "op", "");
    bool found = false;
    for (int i = 0; i < OP__N; i++) if (!strcmp(op, op_name((EndpointOp)i))) { ep->op = (EndpointOp)i; found = true; }
    if (!found) return sfail(c, "endpoint %s: op must be list, get, create, update or delete (got '%s')", ep->id, op);

    cpstr(ep->coll,   sizeof ep->coll,   y_str(e, "collection", ""));
    cpstr(ep->filter, sizeof ep->filter, y_str(e, "filter", ""));
    cpstr(ep->doc,    sizeof ep->doc,    y_str(e, "doc", ""));
    ep->latency_ms      = y_int(e, "latency_ms", 200);
    ep->needs_credential = y_has(e, "requires") &&
        strstr(y_str(e, "requires", ""), "credential") != NULL;
    /* `requires` is a sequence in the handoff's sketch; accept either. */
    const YNode *req = y_get(e, "requires");
    for (size_t i = 0; i < y_count(req); i++) {
        const YNode *r = y_at(req, i);
        if (r && r->kind == Y_SCALAR && !strcmp(r->scalar, "credential_valid")) ep->needs_credential = true;
        else if (r && r->kind == Y_SCALAR) return sfail(c, "endpoint %s: unknown precondition '%s'", ep->id, r->scalar);
    }

    if (!seq_into(c, y_get(e, "fields"),   ep->field,    SPEC_MAX_FIELDS, &ep->nfield,    "fields"))   return false;
    if (!seq_into(c, y_get(e, "required"), ep->required, SPEC_MAX_FIELDS, &ep->nrequired, "required")) return false;
    if (!seq_into(c, y_get(e, "idempotent_on"), ep->idem, SPEC_MAX_KEYS,  &ep->nidem,     "idempotent_on")) return false;

    const YNode *rf = y_get(e, "references");
    if (rf && rf->kind == Y_MAP) {
        if ((int)rf->npair > SPEC_MAX_KEYS) return sfail(c, "endpoint %s: too many references", ep->id);
        for (size_t i = 0; i < rf->npair; i++) {
            cpstr(ep->reffield[ep->nref], RB_NAME_MAX, rf->pair[i].key);
            cpstr(ep->refcoll[ep->nref],  RB_NAME_MAX,
                  rf->pair[i].val->kind == Y_SCALAR ? rf->pair[i].val->scalar : "");
            ep->nref++;
        }
    } else if (rf) {
        return sfail(c, "endpoint %s: references must be a mapping of field to collection", ep->id);
    }

    const YNode *fm = y_get(e, "failure_modes");
    for (size_t i = 0; i < y_count(fm); i++) {
        const YNode *f = y_at(fm, i);
        if (!f || f->kind != Y_SCALAR) return sfail(c, "endpoint %s: bad failure_modes", ep->id);
        if      (!strcmp(f->scalar, "rate_limited"))         ep->failure_modes |= FM_RATE_LIMITED;
        else if (!strcmp(f->scalar, "transient"))            ep->failure_modes |= FM_TRANSIENT;
        else if (!strcmp(f->scalar, "timeout_after_commit")) ep->failure_modes |= FM_TIMEOUT_AFTER_COMMIT;
        else if (!strcmp(f->scalar, "stall"))                ep->failure_modes |= FM_STALL;
        else return sfail(c, "endpoint %s: unknown failure mode '%s'", ep->id, f->scalar);
    }

    const YNode *ex = y_get(e, "examples");
    size_t nex = y_count(ex);
    if (nex > SPEC_MAX_EXAMPLES) return sfail(c, "endpoint %s: too many examples", ep->id);
    for (size_t i = 0; i < nex; i++) {
        const YNode *x = y_at(ex, i);
        if (!x || x->kind != Y_SCALAR) return sfail(c, "endpoint %s: an example is not a line", ep->id);
        cpstr(ep->example[ep->nexample++], sizeof ep->example[0], x->scalar);
    }

    /* A create with no idempotency key and no uniqueness is a duplicate
     * factory. It is allowed — some collections genuinely take duplicates —
     * but it is worth being deliberate about, so it is stated here for the
     * next person reading rather than left implicit. */
    (void)m;
    return true;
}

static bool load_model(Ctx *c, const YNode *root, Model *m)
{
    memset(m, 0, sizeof *m);
    cpstr(m->model,  sizeof m->model,  y_str(root, "model", ""));
    cpstr(m->id,     sizeof m->id,     y_str(root, "id", ""));
    cpstr(m->vendor, sizeof m->vendor, y_str(root, "vendor", ""));
    cpstr(m->kind,   sizeof m->kind,   y_str(root, "kind", ""));
    cpstr(m->theme,  sizeof m->theme,  y_str(root, "theme", ""));
    cpstr(m->doc,    sizeof m->doc,    y_str(root, "doc", ""));
    m->capacity        = y_int(root, "capacity", 600);   /* §5: ~600 users per instance */
    m->credential_days = y_int(root, "credential_days", 0);
    if (!m->id[0])     return sfail(c, "a model file needs an 'id:'");
    if (!m->model[0])  return sfail(c, "model %s has no display name ('model:')", m->id);
    if (!m->vendor[0]) return sfail(c, "model %s has no vendor", m->id);
    if (!m->kind[0])   return sfail(c, "model %s has no kind", m->id);

    const YNode *ifs = y_get(root, "interfaces");
    for (size_t i = 0; i < y_count(ifs); i++) {
        const YNode *it = y_at(ifs, i);
        if (!it || it->kind != Y_SCALAR) return sfail(c, "model %s: bad interfaces", m->id);
        if      (!strcmp(it->scalar, "api")) m->has_api = true;
        else if (!strcmp(it->scalar, "web")) m->has_web = true;
        else return sfail(c, "model %s: interface must be web or api (got '%s')", m->id, it->scalar);
    }
    if (!m->has_api && !m->has_web)
        return sfail(c, "model %s has no interfaces; it cannot be operated at all", m->id);

    /* ---- collections */
    const YNode *st = y_get(root, "state");
    if (st && st->kind == Y_MAP) {
        for (size_t i = 0; i < st->npair; i++) {
            if (m->ncoll >= SPEC_MAX_COLL) return sfail(c, "model %s: too many collections", m->id);
            CollSpec *cs = &m->coll[m->ncoll++];
            memset(cs, 0, sizeof *cs);
            cpstr(cs->name, sizeof cs->name, st->pair[i].key);
            const YNode *cn = st->pair[i].val;
            if (!seq_into(c, y_get(cn, "fields"), cs->field, SPEC_MAX_FIELDS, &cs->nfield, "fields")) return false;
            if (!seq_into(c, y_get(cn, "key"),    cs->key,   SPEC_MAX_KEYS,   &cs->nkey,   "key"))    return false;
            /* Default yes: reuse is the ordinary case, and an author who
             * wants the unforgiving one should have to say so. */
            cs->reuse_key = strcmp(y_str(cn, "reuse_key", "yes"), "no") != 0 &&
                            strcmp(y_str(cn, "reuse_key", "yes"), "false") != 0;
            cs->replicated = strcmp(y_str(cn, "replicated", "no"), "no") != 0 &&
                             strcmp(y_str(cn, "replicated", "no"), "false") != 0;
            cpstr(cs->index_field, RB_NAME_MAX, y_str(cn, "index", ""));
            {
                const char *sc = y_str(cn, "scope", "appliance");
                if      (!strcmp(sc, "service"))   cs->service_scope = true;
                else if (!strcmp(sc, "appliance")) cs->service_scope = false;
                else return sfail(c, "collection %s: scope must be appliance or service", cs->name);
            }
            if (cs->index_field[0] && !in_table((char (*)[RB_NAME_MAX])cs->field, cs->nfield, cs->index_field))
                return sfail(c, "collection %s indexes '%s', which is not one of its fields",
                             cs->name, cs->index_field);
            if (cs->replicated && i == 0)
                return sfail(c, "collection %s is replicated and also the capacity collection; "
                                "the first collection is what an instance's load is measured by",
                             cs->name);
            if (!cs->nfield) return sfail(c, "collection %s has no fields", cs->name);
            for (int k = 0; k < cs->nkey; k++)
                if (!in_table(cs->field, cs->nfield, cs->key[k]))
                    return sfail(c, "collection %s: key '%s' is not one of its fields", cs->name, cs->key[k]);
        }
    }

    /* ---- endpoints */
    const YNode *eps = y_get(root, "endpoints");
    size_t nep = y_count(eps);
    if (nep > SPEC_MAX_EP) return sfail(c, "model %s: too many endpoints", m->id);
    for (size_t i = 0; i < nep; i++) {
        if (!load_endpoint(c, y_at(eps, i), m, &m->ep[m->nep])) return false;
        Endpoint *ep = &m->ep[m->nep];
        const CollSpec *cs = model_coll(m, ep->coll);
        if (!cs) return sfail(c, "endpoint %s acts on collection '%s', which the model does not have",
                              ep->id, ep->coll);
        for (int f = 0; f < ep->nfield; f++)
            if (!in_table((char (*)[RB_NAME_MAX])cs->field, cs->nfield, ep->field[f]))
                return sfail(c, "endpoint %s: field '%s' is not in collection %s", ep->id, ep->field[f], cs->name);
        for (int f = 0; f < ep->nrequired; f++)
            if (!in_table(ep->field, ep->nfield, ep->required[f]))
                return sfail(c, "endpoint %s: required field '%s' is not one it accepts", ep->id, ep->required[f]);
        for (int f = 0; f < ep->nidem; f++)
            if (!in_table(ep->field, ep->nfield, ep->idem[f]))
                return sfail(c, "endpoint %s: idempotent_on '%s' is not a field it accepts", ep->id, ep->idem[f]);
        for (int f = 0; f < ep->nref; f++) {
            if (!in_table(ep->field, ep->nfield, ep->reffield[f]))
                return sfail(c, "endpoint %s: references '%s', which is not a field it accepts",
                             ep->id, ep->reffield[f]);
            const CollSpec *rc = model_coll(m, ep->refcoll[f]);
            if (!rc) return sfail(c, "endpoint %s: '%s' references collection '%s', which does not exist",
                                  ep->id, ep->reffield[f], ep->refcoll[f]);
            if (rc->nkey != 1)
                return sfail(c, "endpoint %s: cannot reference %s; it is not keyed by a single field",
                             ep->id, rc->name);
        }
        if (ep->filter[0] && !in_table((char (*)[RB_NAME_MAX])cs->field, cs->nfield, ep->filter))
            return sfail(c, "endpoint %s: filter '%s' is not in collection %s", ep->id, ep->filter, cs->name);
        if ((ep->op == OP_GET || ep->op == OP_UPDATE || ep->op == OP_DELETE) && !cs->nkey)
            return sfail(c, "endpoint %s is a %s but collection %s has no key to address a record by",
                         ep->id, op_name(ep->op), cs->name);
        if (ep->needs_credential && !m->credential_days)
            return sfail(c, "endpoint %s requires a credential, but %s has no credential_days",
                         ep->id, m->id);
        for (int j = 0; j < m->nep; j++)
            if (!strcmp(m->ep[j].id, ep->id)) return sfail(c, "two endpoints called %s", ep->id);
        m->nep++;
    }

    /* ---- forms. The web UI is generated from these; an appliance with a web
     * interface and no forms cannot be operated by hand, which for the cheap
     * vendor means it cannot be operated at all. */
    const YNode *fs = y_get(root, "forms");
    size_t nf = y_count(fs);
    if (nf > SPEC_MAX_FORMS) return sfail(c, "model %s: too many forms", m->id);
    for (size_t i = 0; i < nf; i++) {
        const YNode *fn = y_at(fs, i);
        Form *f = &m->form[m->nform];
        memset(f, 0, sizeof *f);
        cpstr(f->id,    sizeof f->id,    y_str(fn, "id", ""));
        cpstr(f->calls, sizeof f->calls, y_str(fn, "calls", ""));
        cpstr(f->title, sizeof f->title, y_str(fn, "title", f->id));
        if (!seq_into(c, y_get(fn, "fields"), f->field, SPEC_MAX_FIELDS, &f->nfield, "form fields")) return false;
        const Endpoint *ep = model_endpoint(m, f->calls);
        if (!ep) return sfail(c, "form %s calls '%s', which is not an endpoint of %s", f->id, f->calls, m->id);
        for (int k = 0; k < f->nfield; k++)
            if (!in_table((char (*)[RB_NAME_MAX])ep->field, ep->nfield, f->field[k]))
                return sfail(c, "form %s offers field '%s', which %s does not accept", f->id, f->field[k], ep->id);
        m->nform++;
    }
    if (m->has_web && !m->nform)
        return sfail(c, "model %s claims a web interface but defines no forms", m->id);
    if (!m->has_api && m->nep)
        /* Not an error — the forms need endpoints to call, and the cheap
         * vendor's endpoints exist but are unreachable from a script. That
         * distinction is enforced at call time, in appl.c, where it belongs. */
        (void)0;
    return true;
}

static bool load_ticket(Ctx *c, const Specs *s, const YNode *root, TicketType *t);

/* ----------------------------------------------------------------- files */
typedef struct { char *name; char *text; } SrcFile;

static char *read_file(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n < 0) { fclose(f); return NULL; }
    char *buf = rb_alloc((size_t)n + 1);
    size_t got = fread(buf, 1, (size_t)n, f);
    buf[got] = 0;
    fclose(f);
    return buf;
}

static bool ends_with(const char *s, const char *suf)
{
    size_t a = strlen(s), b = strlen(suf);
    return a >= b && !strcmp(s + a - b, suf);
}

Specs *specs_load(const char *dir, char *err, size_t errcap)
{
    err[0] = 0;
    SrcFile *src = NULL;
    size_t nsrc = 0;

    if (dir) {
        DIR *d = opendir(dir);
        if (!d) { snprintf(err, errcap, "cannot open spec directory %s", dir); return NULL; }
        struct dirent *e;
        while ((e = readdir(d))) {
            if (e->d_name[0] == '.' || e->d_name[0] == '_') continue;
            if (!ends_with(e->d_name, ".yaml")) continue;
            char path[512];
            snprintf(path, sizeof path, "%s/%s", dir, e->d_name);
            char *text = read_file(path);
            if (!text) { closedir(d); snprintf(err, errcap, "cannot read %s", path); return NULL; }
            src = rb_realloc(src, (nsrc + 1) * sizeof *src);
            src[nsrc].name = rb_strdup(e->d_name);
            src[nsrc].text = text;
            nsrc++;
        }
        closedir(d);
        /* readdir order is a filesystem detail, and a world that depends on
         * it is not reproducible. Sort. */
        for (size_t i = 1; i < nsrc; i++)
            for (size_t j = i; j && strcmp(src[j - 1].name, src[j].name) > 0; j--) {
                SrcFile t = src[j - 1]; src[j - 1] = src[j]; src[j] = t;
            }
    } else {
        for (size_t i = 0; i < SPECBIN_N; i++) {
            src = rb_realloc(src, (nsrc + 1) * sizeof *src);
            src[nsrc].name = rb_strdup(specbin[i].name);
            src[nsrc].text = rb_strdup(specbin[i].text);
            nsrc++;
        }
    }

    if (!nsrc) { snprintf(err, errcap, "no specs found%s%s", dir ? " in " : "", dir ? dir : ""); return NULL; }

    Specs *s = rb_alloc(sizeof *s);
    Ctx c = { err, errcap, "", false };
    bool ok = true;

    /* THREE PASSES, IN DEPENDENCY ORDER. Vendors, then the models that name
     * them, then the ticket types whose acceptance checks are validated
     * against those models. File order on disk must not decide whether a spec
     * loads, and readdir order is not even stable. */
    for (int pass = 0; pass < 3 && ok; pass++) {
        for (size_t i = 0; i < nsrc && ok; i++) {
            c.file = src[i].name;
            char perr[RB_ERR_MAX];
            YNode *root = yaml_parse(src[i].text, perr, sizeof perr);
            if (!root) { snprintf(err, errcap, "%s: %s", src[i].name, perr); ok = false; break; }

            int kind = y_has(root, "archetype") ? 0 : (y_has(root, "ticket") ? 2 : 1);
            if (kind != pass) { yaml_free(root); continue; }

            if (pass == 0) {
                s->vendor = rb_realloc(s->vendor, (s->nvendor + 1) * sizeof *s->vendor);
                ok = load_vendor(&c, root, &s->vendor[s->nvendor]);
                if (ok) {
                    for (size_t v = 0; v < s->nvendor; v++)
                        if (!strcmp(s->vendor[v].id, s->vendor[s->nvendor].id))
                            ok = sfail(&c, "two vendors called %s", s->vendor[v].id);
                    if (ok) s->nvendor++;
                }
            } else if (pass == 1) {
                s->model = rb_realloc(s->model, (s->nmodel + 1) * sizeof *s->model);
                ok = load_model(&c, root, &s->model[s->nmodel]);
                if (ok) {
                    Model *m = &s->model[s->nmodel];
                    if (!spec_vendor(s, m->vendor))
                        ok = sfail(&c, "model %s names vendor '%s', which has no spec", m->id, m->vendor);
                    for (size_t k = 0; ok && k < s->nmodel; k++)
                        if (!strcmp(s->model[k].id, m->id)) ok = sfail(&c, "two models called %s", m->id);
                    if (ok) {
                        /* The vendor decides the theme unless the model
                         * overrides it. Handoff §14: if a dozen appliances
                         * share one look, the vendor-quality mechanic dies
                         * quietly, so a model without a theme inherits one
                         * rather than defaulting to Godot grey. */
                        if (!m->theme[0]) cpstr(m->theme, sizeof m->theme, spec_vendor(s, m->vendor)->theme);
                        /* The cheap vendor has no API. Stated in one place --
                         * here -- so a model file cannot accidentally grant
                         * one. */
                        if (spec_vendor(s, m->vendor)->arch == VEN_CHEAP && m->has_api)
                            ok = sfail(&c, "model %s claims an API, but vendor %s is the cheap one",
                                       m->id, m->vendor);
                        if (ok) s->nmodel++;
                    }
                }
            } else {
                s->ticket = rb_realloc(s->ticket, (s->nticket + 1) * sizeof *s->ticket);
                ok = load_ticket(&c, s, root, &s->ticket[s->nticket]);
                if (ok) {
                    for (size_t k = 0; k < s->nticket; k++)
                        if (!strcmp(s->ticket[k].id, s->ticket[s->nticket].id))
                            ok = sfail(&c, "two ticket types called %s", s->ticket[k].id);
                    if (ok) s->nticket++;
                }
            }
            yaml_free(root);
        }
    }

    for (size_t i = 0; i < nsrc; i++) { rb_free(src[i].name); rb_free(src[i].text); }
    rb_free(src);

    if (!ok) { specs_free(s); return NULL; }
    return s;
}

void specs_free(Specs *s)
{
    if (!s) return;
    rb_free(s->vendor);
    rb_free(s->model);
    rb_free(s->ticket);
    rb_free(s);
}

const Vendor *spec_vendor(const Specs *s, const char *id)
{
    for (size_t i = 0; i < s->nvendor; i++) if (!strcmp(s->vendor[i].id, id)) return &s->vendor[i];
    return NULL;
}

const Model *spec_model(const Specs *s, const char *id)
{
    for (size_t i = 0; i < s->nmodel; i++) if (!strcmp(s->model[i].id, id)) return &s->model[i];
    return NULL;
}

const Endpoint *model_endpoint(const Model *m, const char *id)
{
    for (int i = 0; i < m->nep; i++) if (!strcmp(m->ep[i].id, id)) return &m->ep[i];
    return NULL;
}

const CollSpec *model_coll(const Model *m, const char *name)
{
    for (int i = 0; i < m->ncoll; i++) if (!strcmp(m->coll[i].name, name)) return &m->coll[i];
    return NULL;
}

/* ---------------------------------------------------------- ticket types */
/* Loaded here rather than in ticket.c because a ticket type is a spec file
 * like any other, validated by the same pass, and reported by the same error
 * path. The checks are validated against the appliance models: a ticket that
 * verifies a collection no appliance has is a ticket that can never close,
 * and finding that out in a playtest is a wasted afternoon.
 */

const struct TicketType *spec_ticket(const Specs *s, const char *id)
{
    for (size_t i = 0; i < s->nticket; i++) if (!strcmp(s->ticket[i].id, id)) return &s->ticket[i];
    return NULL;
}

/* Does any model of this kind have this collection, with these fields? */
static bool kind_has(const Specs *s, const char *kind, const char *coll,
                     const Field *where, int nwhere, const char *field)
{
    for (size_t i = 0; i < s->nmodel; i++) {
        const Model *m = &s->model[i];
        if (strcmp(m->kind, kind)) continue;
        const CollSpec *cs = model_coll(m, coll);
        if (!cs) continue;
        bool ok = true;
        for (int f = 0; f < nwhere && ok; f++)
            if (!in_table((char (*)[RB_NAME_MAX])cs->field, cs->nfield, where[f].k)) ok = false;
        if (field && !in_table((char (*)[RB_NAME_MAX])cs->field, cs->nfield, field)) ok = false;
        if (ok) return true;
    }
    return false;
}

static bool load_ticket(Ctx *c, const Specs *s, const YNode *root, TicketType *t)
{
    memset(t, 0, sizeof *t);
    cpstr(t->id,           sizeof t->id,           y_str(root, "ticket", ""));
    cpstr(t->subject_kind, sizeof t->subject_kind, y_str(root, "subject", "user"));
    cpstr(t->description,  sizeof t->description,  y_str(root, "description", ""));
    cpstr(t->doc,          sizeof t->doc,          y_str(root, "doc", ""));
    t->sla_minutes = y_int(root, "sla_minutes", 480);
    t->weight      = y_int(root, "weight", 100);
    if (!t->id[0]) return sfail(c, "a ticket file needs a 'ticket:' id");
    if (!t->description[0]) return sfail(c, "ticket %s has no description", t->id);
    if (t->sla_minutes < 1) return sfail(c, "ticket %s has a nonsense SLA", t->id);

    const YNode *acc = y_get(root, "acceptance");
    size_t n = y_count(acc);
    if (!n) return sfail(c, "ticket %s has no acceptance checks; it could never close", t->id);
    if (n > TK_MAX_CHECKS) return sfail(c, "ticket %s has %zu checks; the limit is %d", t->id, n, TK_MAX_CHECKS);

    for (size_t i = 0; i < n; i++) {
        const YNode *cn = y_at(acc, i);
        Check *ck = &t->check[t->ncheck];
        memset(ck, 0, sizeof *ck);
        cpstr(ck->id,        sizeof ck->id,        y_str(cn, "id", ""));
        cpstr(ck->appliance, sizeof ck->appliance, y_str(cn, "appliance", ""));
        cpstr(ck->coll,      sizeof ck->coll,      y_str(cn, "collection", ""));
        cpstr(ck->field,     sizeof ck->field,     y_str(cn, "field", ""));
        cpstr(ck->value,     sizeof ck->value,     y_str(cn, "value", ""));
        cpstr(ck->doc,       sizeof ck->doc,       y_str(cn, "doc", ""));
        cpstr(ck->when,      sizeof ck->when,      y_str(cn, "when", ""));
        cpstr(ck->unless,    sizeof ck->unless,    y_str(cn, "unless", ""));
        /* `bind` names a record for later checks; `of` refers to one already
         * named. They share a slot because a check never does both. */
        cpstr(ck->bind,      sizeof ck->bind,      y_str(cn, "bind", y_str(cn, "of", "")));
        if (!ck->id[0]) return sfail(c, "ticket %s: a check has no id", t->id);
        if (!ck->doc[0]) return sfail(c, "ticket %s: check %s is undocumented, and the player is shown these", t->id, ck->id);

        const char *k = y_str(cn, "check", "");
        if      (!strcmp(k, "exists"))     ck->kind = CHK_EXISTS;
        else if (!strcmp(k, "absent"))     ck->kind = CHK_ABSENT;
        else if (!strcmp(k, "equals"))     ck->kind = CHK_EQUALS;
        else if (!strcmp(k, "convention")) ck->kind = CHK_CONVENTION;
        else if (!strcmp(k, "capacity"))   { ck->kind = CHK_CAPACITY; ck->max_pct = y_int(cn, "max_pct", 85); }
        else return sfail(c, "ticket %s: check %s has an unknown kind '%s'", t->id, ck->id, k);

        const YNode *wh = y_get(cn, "where");
        if (wh && wh->kind == Y_MAP) {
            if ((int)wh->npair > TK_MAX_WHERE) return sfail(c, "ticket %s: check %s matches on too many fields", t->id, ck->id);
            for (size_t f = 0; f < wh->npair; f++) {
                cpstr(ck->where[ck->nwhere].k, RB_NAME_MAX, wh->pair[f].key);
                cpstr(ck->where[ck->nwhere].v, RB_VAL_MAX,
                      wh->pair[f].val->kind == Y_SCALAR ? wh->pair[f].val->scalar : "");
                ck->nwhere++;
            }
        } else if (wh) {
            return sfail(c, "ticket %s: check %s: where must be a mapping", t->id, ck->id);
        }

        if (ck->kind == CHK_CAPACITY) {
            if (!ck->appliance[0])
                return sfail(c, "ticket %s: check %s needs an appliance kind", t->id, ck->id);
            if (ck->max_pct < 1 || ck->max_pct > 100)
                return sfail(c, "ticket %s: check %s has a nonsense max_pct", t->id, ck->id);
            /* The kind may be a placeholder -- service.capacity's subject IS
             * the kind -- in which case there is nothing to check here and it
             * is checked against the world at evaluation time instead. */
            if (ck->appliance[0] != '{') {
                bool any = false;
                for (size_t mi = 0; mi < s->nmodel; mi++)
                    if (!strcmp(s->model[mi].kind, ck->appliance)) any = true;
                if (!any) return sfail(c, "ticket %s: check %s names appliance kind '%s'; no model has it",
                                       t->id, ck->id, ck->appliance);
            }
        } else if (ck->kind == CHK_EXISTS || ck->kind == CHK_ABSENT) {
            if (!ck->appliance[0] || !ck->coll[0])
                return sfail(c, "ticket %s: check %s needs an appliance and a collection", t->id, ck->id);
            if (!ck->nwhere)
                return sfail(c, "ticket %s: check %s matches every record in %s, which proves nothing",
                             t->id, ck->id, ck->coll);
            /* THE CHECK THAT MAKES THE OTHERS WORTH HAVING: a ticket whose
             * acceptance names a collection no appliance has can never close,
             * and a ticket that can never close is a queue that only grows.
             * Caught here, at load, rather than in a playtest. */
            if (!kind_has(s, ck->appliance, ck->coll, ck->where, ck->nwhere, NULL))
                return sfail(c, "ticket %s: check %s wants %s/%s with those fields; no appliance model provides it",
                             t->id, ck->id, ck->appliance, ck->coll);
        } else {
            if (!ck->bind[0])
                return sfail(c, "ticket %s: check %s needs 'of:' naming a record an earlier check bound", t->id, ck->id);
            if (!ck->field[0])
                return sfail(c, "ticket %s: check %s needs a field", t->id, ck->id);
            bool bound = false;
            for (int e = 0; e < t->ncheck; e++)
                if (!strcmp(t->check[e].bind, ck->bind) && t->check[e].kind == CHK_EXISTS) bound = true;
            if (!bound)
                return sfail(c, "ticket %s: check %s refers to '%s', which no earlier check binds",
                             t->id, ck->id, ck->bind);
            if (ck->kind == CHK_EQUALS && !ck->value[0])
                return sfail(c, "ticket %s: check %s has no value to compare against", t->id, ck->id);
        }
        for (int e = 0; e < t->ncheck; e++)
            if (!strcmp(t->check[e].id, ck->id)) return sfail(c, "ticket %s: two checks called %s", t->id, ck->id);
        t->ncheck++;
    }
    return true;
}
