/* /bin/du — how much of the disk each directory is using.
 *
 * The number-one reflex on a full disk, and a full disk is a real fault on
 * this machine: `df` says 100%, nothing is corrupt, and the next question is
 * always "used by WHAT". Without du the only answer available was to `ls -l`
 * every directory by hand and add up the sizes in your head, which is not
 * diagnosis, it is arithmetic.
 *
 * IT AGREES WITH df, and that is a deliberate constraint rather than a happy
 * accident. df reports the sum of every file's bytes divided by 1024; so does
 * du. Real du rounds each file up to a whole block, which would make
 * `du -s /` and `df` disagree by a few percent -- and two tools that disagree
 * about the same number send a player looking for a third one to break the
 * tie. Directories cost no bytes here (they cost an INODE, which is `df -i`),
 * and a symlink costs nothing, exactly as the kernel counts it.
 *
 * /proc is skipped. It is generated by the kernel, is not on the disk df is
 * measuring, and counting it would be the one thing that made the two
 * disagree.
 */
#include "gsys.h"

static char arg[GARG_MAX];
static char *v[GARGS];
static int summary;      /* -s: the total only          */
static int human;        /* -h: K and M rather than K   */

static void put_size(i64 bytes)
{
    if (!human) { g_putpad(bytes / 1024, 8); return; }
    /* Under a kilobyte, -h prints BYTES. Real du would round up to a block
     * and say 4.0K, but this du does not round -- that is what lets it agree
     * with df -- so rounding only in the -h path would make `du -h` and `du`
     * disagree with each other, and "0K" on a directory that plainly has
     * files in it reads as a broken tool. */
    if (bytes < 1024) { g_putn(bytes); g_puts("B  "); return; }
    if (bytes >= 1024 * 1024) {
        g_putn(bytes / (1024 * 1024));
        g_puts(".");
        g_putn((bytes % (1024 * 1024)) * 10 / (1024 * 1024));
        g_puts("M  ");
        return;
    }
    g_putn(bytes / 1024); g_puts("K  ");
}

/* Recursive, with its buffers on the STACK and not in static storage. A
 * static name buffer in a function that calls itself is a bug this project
 * has already had: `find` descended into a directory and came back out with
 * one entry, because the child's readdir had overwritten the parent's. */
static i64 walk(const char *dir, int depth)
{
    char name[128], full[256], tgt[192];
    i64 total = 0;

    if (depth > 16) return 0;                 /* a bind can make a loop */
    /* /proc is generated by the kernel and is not on the disk df measures,
     * so counting it is the one thing that makes the two disagree -- and it
     * did: `du` from / came out 2 K over df because of the per-pid files.
     * Matched on the SUFFIX, because `du` with no argument walks `.` and the
     * path it builds is ./proc, which an equality test does not catch. */
    if (g_streq(dir, "/proc") || g_endswith(dir, "/proc")) return 0;

    for (int i = 0; i < 4096; i++) {
        if (g_readdir(dir, i, name) < 0) break;
        g_copy(full, dir, sizeof full);
        if (!g_streq(dir, "/")) g_cat(full, "/", sizeof full);
        g_cat(full, name, sizeof full);

        /* A symlink is not followed and costs nothing, which is how the
         * kernel counts it -- and following one would count /boot/vmnomuz
         * twice and let a link into a parent run forever. */
        if (g_readlink(full, tgt, sizeof tgt) > 0) continue;

        NomStat st;
        if (g_stat(full, &st) != 0) continue;
        if (st.kind == NOM_KIND_DIR) {
            i64 sub = walk(full, depth + 1);
            total += sub;
            if (!summary) { put_size(sub); g_putln(full); }
        } else {
            total += st.size;
        }
    }
    return total;
}

void _start(void)
{
    g_getarg(arg, sizeof arg);
    int n = g_argv(arg, v);
    g_argv_warn("du");

    int nop = 0;
    for (int i = 0; i < n; i++) {
        if (v[i][0] != '-' || !v[i][1]) { v[nop++] = v[i]; continue; }
        int bad = 0;
        for (const char *f = v[i] + 1; *f; f++) {
            if (*f == 's') summary = 1;
            else if (*f == 'h') human = 1;
            else bad = 1;
        }
        if (bad) {
            g_puts("du: "); g_puts(v[i]); g_putln(": not a flag this du has");
            g_putln("usage: du [-s] [-h] [dir ...]");
            g_exit(2);
        }
    }

    int rc = 0;
    if (nop == 0) { v[0] = "."; nop = 1; }
    for (int i = 0; i < nop; i++) {
        NomStat st;
        if (g_stat(v[i], &st) != 0) {
            g_puts("du: "); g_puts(v[i]); g_putln(": not found");
            rc = 1;
            continue;
        }
        if (st.kind != NOM_KIND_DIR) { put_size(st.size); g_putln(v[i]); continue; }
        i64 tot = walk(v[i], 0);
        put_size(tot);
        g_putln(v[i]);
    }
    g_exit(rc);
}
