#!/bin/sh
# mkguest.sh — compile the guest userland to rv64 and embed it as C arrays.
#
# Lifted from ~/NOMINAL/tools/mkguest.sh, with one program added: rb, which is
# how a script on the machine reaches the game.
#
# The generated machine/guestbin.h is COMMITTED, so building or shipping
# RUNBOOK needs no riscv toolchain -- only changing a guest program does. That
# matters more here than it did there: decision 3 is one self-contained binary
# per platform, and a build that needs clang with a riscv target is a build
# most people cannot do.
#
# THESE ARE REAL PROGRAMS. The boot loads them off the machine's disk and
# executes them on the emulated CPU, instruction by instruction. Corrupting
# one produces a genuine trap, not a scripted error message -- which is the
# whole reason the emulator is here at all.
set -eu
OUT=machine/guestbin.h
CC=${GUESTCC:-clang}
CFLAGS="--target=riscv64-unknown-elf -march=rv64im -mabi=lp64 -nostdlib
        -ffreestanding -fno-builtin -Os -Wall -Wextra -Iguest -Imachine"

command -v "$CC" >/dev/null 2>&1 || { echo "mkguest: no $CC; keeping $OUT"; exit 0; }
command -v ld.lld >/dev/null 2>&1 || { echo "mkguest: no ld.lld; keeping $OUT"; exit 0; }

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
{
  echo "/* guestbin.h — GENERATED by tools/mkguest.sh. Do not edit."
  echo " *"
  echo " * The guest userland, compiled for our rv64 machine. These are real"
  echo " * programs: the boot loads them off the disk and executes them, and"
  echo " * corrupting one produces a genuine cpu trap or ELF-load failure."
  echo " */"
  echo "#ifndef NOM_GUESTBIN_H"
  echo "#define NOM_GUESTBIN_H"
  echo
} > "$TMP/h"

for p in init rc svcinit login sh ls cat ps ns pkg stat chmod mount umount chroot links cp mv rm touch grep head uname whoami df man zbl-install zbl-mkconfig mkinitrd getty fsck mountall sed ed wc echo blkid svc kill syslogd netd udevd crond ntpd httpd nft auditd sshd postfix ldd dmesg rcon find netstat ping reboot open nomde fortune cowsay sl du tail mkdir rev seq test rot13 ip arp traceroute tcpdump ss voice rb py; do
    # -Ttext keeps every program at a fixed load address: same layout every
    # run, on every host, which is one more thing determinism does not have
    # to be careful about.
    # A guest program that fails to compile used to leave the PREVIOUS
    # guestbin.h in place and say nothing useful, so the game silently kept
    # running the old binary and the change appeared to have no effect. Say
    # so, loudly, and stop.
    # SOME PROGRAMS ARE MORE THAN ONE FILE. /bin/py is the lexer, compiler
    # and bytecode VM lifted from NOMINAL plus a guest heap, and those stay
    # SEPARATE translation units so they remain byte-identical to the
    # originals -- and because two of them have a static `emit`.
    EXTRA=""
    [ -d "guest/$p.d" ] && EXTRA=$(ls guest/$p.d/*.c 2>/dev/null || true)
    # -Iguest/$p.d FIRST, ahead of everything in CFLAGS. py.c includes
    # "nom.h" and there are two of those -- the host shim in machine/ that
    # lets NOMINAL's kernel compile here, and the guest one that lets its
    # LANGUAGE compile here. Include order is the only thing that decides
    # which, and getting it wrong produced a fatal error about a header the
    # guest has no business seeing.
    if ! $CC -Iguest/$p.d $CFLAGS -fuse-ld=lld -Wl,-Ttext=0x10000 -Wl,--build-id=none \
             -o "$TMP/$p.elf" "guest/$p.c" $EXTRA; then
        echo "mkguest: FAILED to build guest/$p.c -- $OUT left UNCHANGED" >&2
        exit 1
    fi
    python3 - "$TMP/$p.elf" "$p" >> "$TMP/h" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
# A C identifier cannot contain a hyphen, and zbl-install is a perfectly
# reasonable program name, so the symbol is sanitised rather than the file.
name = sys.argv[2].replace('-', '_')
print(f"static const unsigned char GUEST_{name.upper()}[] = {{")
for i in range(0, len(data), 12):
    print("    " + " ".join(f"0x{b:02x}," for b in data[i:i+12]))
print("};")
print(f"#define GUEST_{name.upper()}_LEN {len(data)}")
print()
PY
done

{ echo "#endif /* NOM_GUESTBIN_H */"; } >> "$TMP/h"
mv "$TMP/h" "$OUT"
echo "mkguest: wrote $OUT ($(wc -c < "$OUT") bytes)"
