#!/bin/sh
# Embed specs/*.yaml into core/specbin.h.
#
# WHY THE GENERATED HEADER IS COMMITTED: decision 3 is a single self-contained
# binary per platform, and an appliance library that lives in a directory next
# to the executable is not that -- it is a thing players lose, antivirus eats,
# and Steam updates out of order. So the specs ship inside the binary.
#
# They are still authored as files, because M8 has agents writing appliances
# and nobody should hand-edit a C string literal. Run this after changing a
# spec; `make` will remind you if you forget, because specbin.h is a
# prerequisite of every object that includes it.
#
# Iterating on a spec without a rebuild: runbook --specs specs/
set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
OUT=core/specbin.h

{
  echo "/* GENERATED by tools/mkspecs.sh from the specs directory. Do not edit. */"
  echo "#ifndef RB_SPECBIN_H"
  echo "#define RB_SPECBIN_H"
  echo ""
  echo "typedef struct { const char *name; const char *text; } SpecBin;"
  echo ""
  echo "static const SpecBin specbin[] = {"
  for f in specs/*.yaml; do
    [ -e "$f" ] || continue
    base=$(basename "$f")
    case "$base" in _*) continue ;; esac
    printf '    { "%s",\n' "$base"
    # One C string per line, so a diff of this file is readable and a spec
    # error's line number still means something.
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/      "/' -e 's/$/\\n"/' "$f"
    printf '    },\n'
  done
  echo "};"
  echo ""
  echo "#define SPECBIN_N (sizeof specbin / sizeof specbin[0])"
  echo ""
  echo "#endif"
} > "$OUT"

echo "mkspecs: $(ls specs/*.yaml 2>/dev/null | grep -cv '/_') specs -> $OUT ($(wc -c <"$OUT") bytes)"
